name: full_svg_flutter
description: An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
repository: https://github.com/denisnadey/flutter_full_svg_support
issue_tracker: https://github.com/denisnadey/flutter_full_svg_support/issues
version: 1.0.0

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  meta: ^1.17.0
  vector_graphics: ^1.1.13
  vector_graphics_codec: ^1.1.11+1
  vector_graphics_compiler: ^1.1.14
  xml: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - svg
  - vector-graphics
