// ignore_for_file: avoid_print
/// Frame-diff tool for "Glowing Gummies Graphic Art Animation".
///
/// Renders the SVG (with SVGator player inlined) at 300 evenly-spaced time
/// points across the full 8900 ms animation, saves each frame as a PNG, and
/// prints a per-frame pixel-change percentage so you can spot buggy frames
/// quickly.
///
/// Run:
///   flutter test test/animation/glowing_gummies_frame_diff_test.dart \
///     --no-pub --timeout none
///
/// Output: test/golden_comparison/frame_diffs/gummies_NNNN.png  (300 files)
///         Console: frame index, seek-ms, changed-pixel-%.
///
/// Requires: test/golden_comparison/svg_fixtures/glowing_gummies_inlined.svg
///   (generated by scripts/gen_gummies_inlined.py or the python snippet in README)
library;

import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:full_svg_flutter/src/animation/animated_svg_picture.dart';

// ─── Config ────────────────────────────────────────────────────────────────

const int    _frameCount    = 300;
const int    _animDurationMs = 8900;
const double _svgWidth      = 700;
const double _svgHeight     = 400;
const String _fixturePath   =
    'test/golden_comparison/svg_fixtures/glowing_gummies_inlined.svg';
const String _outDir        = 'test/golden_comparison/frame_diffs';

// ─── Helpers ───────────────────────────────────────────────────────────────

String _svgContent() => File(_fixturePath).readAsStringSync();

Future<Uint8List?> _captureFrame(GlobalKey key, WidgetTester tester) async {
  return tester.runAsync<Uint8List?>(() async {
    final boundary =
        key.currentContext?.findRenderObject() as RenderRepaintBoundary?;
    if (boundary == null) return null;
    final image = await boundary.toImage(pixelRatio: 1.0);
    final bd = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
    image.dispose();
    if (bd == null) return null;
    return bd.buffer.asUint8List();
  });
}

/// Encodes RGBA bytes as a minimal PNG and writes it to [path].
Future<void> _savePng(Uint8List rgba, int w, int h, String path) async {
  final completer = Completer<ui.Image>();
  ui.decodeImageFromPixels(
    rgba, w, h, ui.PixelFormat.rgba8888,
    (img) => completer.complete(img),
  );
  final image = await completer.future;
  final bd = await image.toByteData(format: ui.ImageByteFormat.png);
  image.dispose();
  if (bd == null) return;
  final f = File(path);
  await f.parent.create(recursive: true);
  await f.writeAsBytes(bd.buffer.asUint8List());
}

/// Returns the fraction of pixels that differ between [a] and [b] by > [threshold].
double _diffFraction(Uint8List a, Uint8List b, {int threshold = 10}) {
  assert(a.length == b.length);
  int changed = 0;
  for (int i = 0; i < a.length; i += 4) {
    final dr = (a[i]   - b[i]).abs();
    final dg = (a[i+1] - b[i+1]).abs();
    final db = (a[i+2] - b[i+2]).abs();
    if (dr > threshold || dg > threshold || db > threshold) changed++;
  }
  return changed / (a.length ~/ 4);
}

/// Pumps the animation forward by [durationMs] ms worth of vsync frames.
/// Each pump advances the SchedulerBinding clock by ~16ms (60 fps).
Future<void> _advanceMs(WidgetTester tester, int durationMs) async {
  const frameDuration = Duration(milliseconds: 16);
  final frames = (durationMs / 16).ceil().clamp(1, 200);
  for (var i = 0; i < frames; i++) {
    await tester.pump(frameDuration);
  }
}

// ─── Test ──────────────────────────────────────────────────────────────────

void main() {
  // Skip automatically in CI (no GUMMIES_FRAMES env var set).
  final runFrames = Platform.environment['GUMMIES_FRAMES'] == '1';

  testWidgets(
    'generate 300 frame diffs for glowing gummies animation',
    skip: !runFrames,
    (tester) async {
      tester.view.physicalSize = const Size(_svgWidth, _svgHeight);
      tester.view.devicePixelRatio = 1.0;

      final svg = _svgContent();
      final key = GlobalKey();

      await tester.pumpWidget(
        MaterialApp(
          debugShowCheckedModeBanner: false,
          home: Scaffold(
            backgroundColor: Colors.transparent,
            body: RepaintBoundary(
              key: key,
              child: SizedBox(
                width: _svgWidth,
                height: _svgHeight,
                child: AnimatedSvgPicture.string(
                  svg,
                  width: _svgWidth,
                  height: _svgHeight,
                  fit: BoxFit.fill,
                  autoPlay: false, // we drive time manually
                ),
              ),
            ),
          ),
        ),
      );

      // Let the SVGator bootstrap + player scripts execute.
      await tester.pump();
      await tester.runAsync(
        () => Future<void>.delayed(const Duration(milliseconds: 600)),
      );
      await tester.pump();
      await tester.pump(const Duration(milliseconds: 100));

      Uint8List? prevPixels;
      int width  = _svgWidth.toInt();
      int height = _svgHeight.toInt();

      final msPerFrame = _animDurationMs / _frameCount;

      print('\n=== Glowing Gummies: ${'_frameCount'} frame diff capture ===');
      print(
        'outDir: $_outDir   size: ${width}x$height   '
        'duration: ${_animDurationMs}ms   step: ${msPerFrame.toStringAsFixed(1)}ms',
      );

      for (int frame = 0; frame < _frameCount; frame++) {
        final seekMs = (frame * msPerFrame).round();

        // Inject JS to seek the SVGator player to [seekMs].
        // The player exposes: svgEl.svgatorPlayer.ready(player => player.seek(ms))
        // We cannot call that directly from Dart, so we advance the rAF clock.
        // Advance by the delta from previous step.
        final deltaMs = frame == 0 ? seekMs : msPerFrame.round();
        await _advanceMs(tester, deltaMs.clamp(1, 500));

        final pixels = await _captureFrame(key, tester);
        if (pixels == null) {
          print('frame $frame: capture failed');
          continue;
        }

        // Compute diff vs previous frame.
        final diffPct = prevPixels != null
            ? _diffFraction(prevPixels!, pixels) * 100
            : 0.0;
        prevPixels = pixels;

        // Save PNG.
        final framePath =
            '$_outDir/gummies_${frame.toString().padLeft(4, '0')}.png';
        await _savePng(pixels, width, height, framePath);

        print(
          'frame ${frame.toString().padLeft(3)}  '
          't=${seekMs.toString().padLeft(5)}ms  '
          'Δ=${diffPct.toStringAsFixed(2).padLeft(6)}%  '
          '$framePath',
        );
      }

      // Drain network timer.
      await tester.runAsync(
        () => Future<void>.delayed(const Duration(milliseconds: 500)),
      );
      await tester.pump();

      print('\nDone. Frames written to $_outDir/');
    },
  );

  // ── Always-run sanity checks ──────────────────────────────────────────────

  test('gummies inlined fixture exists', () {
    expect(
      File(_fixturePath).existsSync(),
      isTrue,
      reason: 'Run scripts/gen_gummies_inlined.py first',
    );
  });

  test('animation duration from script data is ~8900ms', () {
    final svg = _svgContent();
    final ts = RegExp(r'"t":(\d+)').allMatches(svg)
        .map((m) => int.parse(m.group(1)!))
        .toList();
    expect(ts, isNotEmpty);
    final maxT = ts.reduce((a, b) => a > b ? a : b);
    expect(maxT, greaterThanOrEqualTo(8000),
        reason: 'Animation should span ~8900ms; got $maxT');
  });

  testWidgets('static render: no crash, has visible pixels', (tester) async {
    tester.view.physicalSize = const Size(_svgWidth, _svgHeight);
    tester.view.devicePixelRatio = 1.0;

    final svg = _svgContent();
    final key = GlobalKey();

    await tester.pumpWidget(
      MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          backgroundColor: Colors.transparent,
          body: RepaintBoundary(
            key: key,
            child: SizedBox(
              width: _svgWidth,
              height: _svgHeight,
              child: AnimatedSvgPicture.string(
                svg,
                width: _svgWidth,
                height: _svgHeight,
                fit: BoxFit.fill,
              ),
            ),
          ),
        ),
      ),
    );

    await tester.pump();
    await tester.runAsync(
      () => Future<void>.delayed(const Duration(milliseconds: 500)),
    );
    await tester.pump();

    final pixels = await tester.runAsync<Uint8List?>(() async {
      final boundary =
          key.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) return null;
      final image = await boundary.toImage(pixelRatio: 1.0);
      final bd = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
      image.dispose();
      return bd?.buffer.asUint8List();
    });

    expect(pixels, isNotNull);

    // At least 5% of pixels should be visible (non-transparent).
    int visible = 0;
    for (int i = 3; i < pixels!.length; i += 4) {
      if (pixels[i] > 10) visible++;
    }
    final visibleFraction = visible / (pixels.length ~/ 4);
    print('[Gummies] visible fraction: ${(visibleFraction * 100).toStringAsFixed(1)}%');
    expect(visibleFraction, greaterThan(0.05),
        reason: 'Expected at least 5% visible pixels at t=0');

    // Background should be dark (navy #1b2238 ≈ RGB(27,34,56)).
    // Sample corners.
    int darkCorners = 0;
    final w = _svgWidth.toInt();
    final h = _svgHeight.toInt();
    for (final (cx, cy) in [(10, 10), (w - 10, 10), (10, h - 10), (w - 10, h - 10)]) {
      final idx = (cy * w + cx) * 4;
      if (idx + 3 >= pixels.length) continue;
      final r = pixels[idx], g = pixels[idx+1], b = pixels[idx+2], a = pixels[idx+3];
      if (a > 200 && r < 80 && g < 80 && b < 100) darkCorners++;
    }
    print('[Gummies] dark corners: $darkCorners / 4');
    expect(darkCorners, greaterThanOrEqualTo(2),
        reason: 'Expected dark navy background at corners');

    // Drain network.
    await tester.runAsync(
      () => Future<void>.delayed(const Duration(milliseconds: 500)),
    );
    await tester.pump();
  });

  // ── Black-blob regression: inner-shadow filter produces shadow color not black ──
  //
  // Before the fix, feColorMatrix constant column values were passed un-scaled
  // (SVG [0,1] range) to Flutter's ColorFilter.matrix which treats the constant
  // column in [0,255] range → constants were ~255× too small → nearly-black output.
  // Also, feComposite arithmetic(k2=-1,k3=1) fell through to srcOver instead of dstOut.

  testWidgets('feColorMatrix constant column is scaled correctly (not near-zero)', (tester) async {
    // A rect painted through feColorMatrix that replaces all channels with constants.
    // SVG values "0 0 0 0 1  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0" → solid RED.
    const svg = '''
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <filter id="cm">
      <feColorMatrix type="matrix"
        values="0 0 0 0 1  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0"/>
    </filter>
  </defs>
  <rect x="10" y="10" width="80" height="80" fill="blue" filter="url(#cm)"/>
</svg>''';

    tester.view.physicalSize = const Size(100, 100);
    tester.view.devicePixelRatio = 1.0;

    final key = GlobalKey();
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.black,
        body: RepaintBoundary(key: key, child: SizedBox(
          width: 100, height: 100,
          child: AnimatedSvgPicture.string(svg, width: 100, height: 100),
        )),
      ),
    ));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 100));

    final pixels = await tester.runAsync<Uint8List?>(() async {
      final b = key.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (b == null) return null;
      final img = await b.toImage(pixelRatio: 1.0);
      final bd = await img.toByteData(format: ui.ImageByteFormat.rawRgba);
      img.dispose();
      return bd?.buffer.asUint8List();
    });

    expect(pixels, isNotNull);
    final idx = (50 * 100 + 50) * 4;
    final r = pixels![idx], g = pixels[idx+1], b = pixels[idx+2];
    print('[CM constant] center: rgb($r, $g, $b)');
    expect(r, greaterThan(200),
        reason: 'feColorMatrix constant "1" must produce ~255 red; got $r. '
            'Constant column must be scaled ×255 for Flutter.');
    expect(g, lessThan(20), reason: 'Green should be ~0');
    expect(b, lessThan(20), reason: 'Blue should be ~0');
  });

  testWidgets('inner-shadow feComposite arithmetic does not produce opaque black blobs', (tester) async {
    // Two-layer SVG:
    //   - bottom: pink fill (visible shape)
    //   - top: same shape with inner-shadow filter (adds shadow at inner edges)
    // At the center, the inner-shadow layer should be transparent → bottom pink shows.
    // Before the fix, the filter produced solid black blobs covering the pink.
    const svg = '''
<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <filter id="innerShadow" x="-50%" y="-50%" width="200%" height="200%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="3 3"/>
      <feOffset dx="3" dy="3"/>
      <feComposite operator="arithmetic" k2="-1" k3="1" in2="SourceGraphic"/>
      <feColorMatrix type="matrix"
        values="0 0 0 0 0.341  0 0 0 0 0.133  0 0 0 0 0.282  0 0 0 0.5 0"/>
    </filter>
  </defs>
  <!-- Bottom: visible pink fill -->
  <rect x="40" y="40" width="120" height="120" fill="#fa92d0"/>
  <!-- Top: inner-shadow layer — should be transparent at center so pink shows -->
  <rect x="40" y="40" width="120" height="120" fill="#582248" filter="url(#innerShadow)"/>
</svg>''';

    tester.view.physicalSize = const Size(200, 200);
    tester.view.devicePixelRatio = 1.0;

    final key = GlobalKey();
    await tester.pumpWidget(MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        body: RepaintBoundary(key: key, child: SizedBox(
          width: 200, height: 200,
          child: AnimatedSvgPicture.string(svg, width: 200, height: 200),
        )),
      ),
    ));
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 100));

    final pixels = await tester.runAsync<Uint8List?>(() async {
      final b = key.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (b == null) return null;
      final img = await b.toImage(pixelRatio: 1.0);
      final bd = await img.toByteData(format: ui.ImageByteFormat.rawRgba);
      img.dispose();
      return bd?.buffer.asUint8List();
    });

    expect(pixels, isNotNull);
    // Center of the rect (100, 100). The bottom pink layer should dominate.
    final idx = (100 * 200 + 100) * 4;
    final r = pixels![idx], g = pixels[idx+1], b = pixels[idx+2], a = pixels[idx+3];
    print('[InnerShadow] center: rgb($r, $g, $b, a=$a)');

    // The pink fill (#fa92d0 ≈ RGB 250,146,208) should be visible at center.
    // Before the fix: solid black (0,0,0) covered the pink.
    expect(r, greaterThan(100),
        reason: 'Inner-shadow center must not be solid black; '
            'pink fill (#fa92d0) should show through. Got rgb($r,$g,$b)');
    expect(r, greaterThan(g),
        reason: 'Pink has high R; got rgb($r,$g,$b)');
  });
}
