import 'dart:convert';
import 'dart:io';

void main() {
  final repoRoot = _resolveRepoRoot();
  final manifestFile = File(
    '$repoRoot/test/w3c/manifest/w3c_static_accepted_manifest.json',
  );
  final suiteSvgDir = Directory('$repoRoot/W3C_SVG_11_TestSuite/svg');
  final outFile = File('$repoRoot/example/lib/generated/w3c_test_catalog.dart');

  if (!manifestFile.existsSync()) {
    stderr.writeln('Manifest not found: ${manifestFile.path}');
    exitCode = 1;
    return;
  }
  if (!suiteSvgDir.existsSync()) {
    stderr.writeln('W3C suite svg dir not found: ${suiteSvgDir.path}');
    exitCode = 1;
    return;
  }

  final manifestRaw = manifestFile.readAsStringSync();
  final manifestJson = jsonDecode(manifestRaw);
  if (manifestJson is! Map<String, dynamic>) {
    stderr.writeln('Invalid manifest JSON: ${manifestFile.path}');
    exitCode = 1;
    return;
  }

  final staticAccepted = <String>{};
  final entries = manifestJson['entries'];
  if (entries is List) {
    for (final item in entries) {
      if (item is Map) {
        final name = item['name'];
        if (name is String && name.isNotEmpty) {
          staticAccepted.add(name);
        }
      }
    }
  }

  final svgFiles =
      suiteSvgDir
          .listSync()
          .whereType<File>()
          .where((file) => file.path.toLowerCase().endsWith('.svg'))
          .toList(growable: false)
        ..sort((a, b) => a.path.compareTo(b.path));

  final buffer = StringBuffer();
  final generatedAt = DateTime.now().toUtc().toIso8601String();

  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.');
  buffer.writeln(
    '// Generated by tool/w3c_suite/generate_playground_catalog.dart',
  );
  buffer.writeln('// Generated at (UTC): $generatedAt');
  buffer.writeln();
  buffer.writeln('class W3cPlaygroundCase {');
  buffer.writeln('  const W3cPlaygroundCase({');
  buffer.writeln('    required this.name,');
  buffer.writeln('    required this.category,');
  buffer.writeln('    required this.svgPath,');
  buffer.writeln('    required this.inStaticAccepted,');
  buffer.writeln('  });');
  buffer.writeln();
  buffer.writeln('  final String name;');
  buffer.writeln('  final String category;');
  buffer.writeln('  final String svgPath;');
  buffer.writeln('  final bool inStaticAccepted;');
  buffer.writeln('}');
  buffer.writeln();
  buffer.writeln(
    'const int kW3cPlaygroundStaticAcceptedCount = ${staticAccepted.length};',
  );
  buffer.writeln('const int kW3cPlaygroundTotalCount = ${svgFiles.length};');
  buffer.writeln();
  buffer.writeln(
    'const List<W3cPlaygroundCase> kW3cPlaygroundCases = <W3cPlaygroundCase>[',
  );

  for (final file in svgFiles) {
    final fileName = file.uri.pathSegments.isNotEmpty
        ? file.uri.pathSegments.last
        : '';
    final caseName = fileName.replaceFirst(
      RegExp(r'\.svg$', caseSensitive: false),
      '',
    );
    if (caseName.isEmpty) {
      continue;
    }
    final category = _categoryFromName(caseName);
    final svgPath = 'W3C_SVG_11_TestSuite/svg/$fileName';
    final inStaticAccepted = staticAccepted.contains(caseName);
    buffer.writeln('  W3cPlaygroundCase(');
    buffer.writeln("    name: '${_escape(caseName)}',");
    buffer.writeln("    category: '${_escape(category)}',");
    buffer.writeln("    svgPath: '${_escape(svgPath)}',");
    buffer.writeln('    inStaticAccepted: $inStaticAccepted,');
    buffer.writeln('  ),');
  }

  buffer.writeln('];');

  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(buffer.toString());
  stdout.writeln('Generated ${outFile.path}');
  stdout.writeln('Total cases: ${svgFiles.length}');
  stdout.writeln('Static accepted: ${staticAccepted.length}');
}

String _resolveRepoRoot() {
  final scriptFile = File.fromUri(Platform.script);
  return scriptFile.parent.parent.parent.path;
}

String _categoryFromName(String caseName) {
  final separator = caseName.indexOf('-');
  if (separator <= 0) {
    return 'misc';
  }
  return caseName.substring(0, separator).toLowerCase();
}

String _escape(String input) {
  return input.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}
